version: 0.1
http:
    addr: :5000
    secret: notasecret123
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
auth:
    token:
        realm: http://host.docker.internal:3001/registry/token
        service: registry.sunodo.io
        issuer: api.sunodo.io
        rootcertbundle: /keys/registry.crt
