version: "3.9"

services:
    database_creator:
        image: postgres:15-alpine
        command: ["createdb", "squid"]
        environment:
            PGHOST: ${SUNODO_DB_HOST:-database}
            PGPORT: ${SUNODO_DB_PORT:-5432}
            PGUSER: ${SUNODO_DB_USER:-postgres}
            PGPASSWORD: ${SUNODO_DB_PASS:-password}
            PGDATABASE: ${SUNODO_DB_NAME:-postgres}

    explorer_api:
        image: cartesi/rollups-explorer-api:0.1.0
        environment:
            DB_NAME: ${SUNODO_SQUID_DB_NAME:-squid}
            DB_PORT: ${SUNODO_DB_PORT:-5432}
            DB_HOST: ${SUNODO_DB_HOST:-database}
            DB_PASS: ${SUNODO_DB_PASS:-password}
            GQL_PORT: 4350
        expose:
            - 4350
        command: ["sqd", "serve:prod"]
        depends_on:
            database_creator:
                condition: service_completed_successfully

    squid_processor:
        image: cartesi/rollups-explorer-api:0.1.0
        environment:
            CHAIN_ID: ${CHAIN_ID:-31337}
            RPC_ENDPOINT: ${RPC_URL:-http://anvil:8545}
            DB_NAME: ${SUNODO_SQUID_DB_NAME:-squid}
            DB_PORT: ${SUNODO_DB_PORT:-5432}
            DB_HOST: ${SUNODO_DB_HOST:-database}
            DB_PASS: ${SUNODO_DB_PASS:-password}
        command: ["sqd", "process:prod"]
        depends_on:
            database_creator:
                condition: service_completed_successfully

    explorer:
        image: cartesi/rollups-explorer:0.1.1
        expose:
            - 3000
        depends_on:
            database_creator:
                condition: service_completed_successfully

    traefik-config-generator:
        environment:
            TRAEFIK_CONFIG_EXPLORER_API: |
                http:
                    routers:
                        explorer-api:
                            rule: "PathPrefix(`/explorer-api`)"
                            middlewares:
                                - "remove-explorer-api-prefix"
                            service: explorer-api
                    middlewares:
                        remove-explorer-api-prefix:
                            replacePathRegex:
                                regex: "^/explorer-api/(.*)"
                                replacement: "/$1"
                    services:
                        explorer-api:
                            loadBalancer:
                                servers:
                                    - url: "http://explorer_api:4350"
            TRAEFIK_CONFIG_EXPLORER: |
                http:
                    routers:
                        explorer:
                            rule: "PathPrefix(`/explorer`)"
                            service: explorer
                    services:
                        explorer:
                            loadBalancer:
                                servers:
                                    - url: "http://explorer:3000"
