services:
    database_creator:
        image: postgres:15-alpine
        command: ["createdb", "squid"]
        environment:
            PGHOST: ${PGHOST:-database}
            PGPORT: ${PGPORT:-5432}
            PGUSER: ${PGUSER:-postgres}
            PGPASSWORD: ${PGPASSWORD:-password}
            PGDATABASE: ${PGDATABASE:-postgres}

    explorer_api:
        image: cartesi/rollups-explorer-api:0.4.0
        environment:
            DB_NAME: ${PGDATABASE:-squid}
            DB_PORT: ${PGPORT:-5432}
            DB_HOST: ${PGHOST:-database}
            DB_PASS: ${PGPASSWORD:-password}
            GQL_PORT: 4350
        expose:
            - 4350
        command: ["sqd", "serve:prod"]
        depends_on:
            database_creator:
                condition: service_completed_successfully

    squid_processor:
        image: cartesi/rollups-explorer-api:0.4.0
        environment:
            CHAIN_ID: ${CHAIN_ID:-31337}
            RPC_URL_31337: ${RPC_URL:-http://anvil:8545}
            DB_NAME: ${PGDATABASE:-squid}
            DB_PORT: ${PGPORT:-5432}
            DB_HOST: ${PGHOST:-database}
            DB_PASS: ${PGPASSWORD:-password}
        command: ["sqd", "process:prod"]
        depends_on:
            database_creator:
                condition: service_completed_successfully

    explorer:
        image: cartesi/rollups-explorer:0.9.0
        expose:
            - 3000
        depends_on:
            database_creator:
                condition: service_completed_successfully

    prompt:
        image: debian:bookworm-slim
        environment:
            PROMPT_TXT_04_EXPLORER: "Explorer running at http://localhost:${CARTESI_LISTEN_PORT}/explorer/"

    traefik-config-generator:
        environment:
            TRAEFIK_CONFIG_EXPLORER_API: |
                http:
                    routers:
                        explorer-api:
                            rule: "PathPrefix(`/explorer-api`)"
                            middlewares:
                                - "remove-explorer-api-prefix"
                            service: explorer-api
                    middlewares:
                        remove-explorer-api-prefix:
                            replacePathRegex:
                                regex: "^/explorer-api/(.*)"
                                replacement: "/$1"
                    services:
                        explorer-api:
                            loadBalancer:
                                servers:
                                    - url: "http://explorer_api:4350"
            TRAEFIK_CONFIG_EXPLORER: |
                http:
                    routers:
                        explorer:
                            rule: "PathPrefix(`/explorer`)"
                            service: explorer
                    services:
                        explorer:
                            loadBalancer:
                                servers:
                                    - url: "http://explorer:3000"
